const APP_NAME = require('../app-name')

const compile = (start, campus, dest, when) =>
  when({
    week: (n) => n,
    mon: () => 0,
    tue: () => 1,
    wed: () => 2,
    thu: () => 3,
    fri: () => 4,

    welly: () => (c) => c === 'welly',
    akl: () => (c) => c === 'akl',
    online: () => (c) => c === 'online',
    all: () => () => true,
    except:
      (...cs) =>
      (c) =>
        cs.every((f) => !f(c)),
    on: (week, day, matchCampus, act) => {
      if (!matchCampus(campus)) {
        return []
      }
      const target = new Date(
        +start + 24 * 60 * 60 * 1000 * ((week - 1) * 7 + day)
      )
        .toISOString()
        .slice(0, 10)

      return [
        `// week ${week}, day ${
          day + 1
        }\n  on('${target}').deploy(${act}).to(${JSON.stringify(dest)})`,
      ]
    },
    deploy: (...items) => items.map((x) => JSON.stringify(x)).join(', '),
    schedule: (...items) =>
      `// file generated by ${APP_NAME}
module.exports = on => {
  // Cohort starting ${start.toString().slice(0, 10)}
  ${[].concat(...items).join('\n\n  ')}}\n`,
  })

module.exports = compile
