/**
 * @type {import('./Algebra.js').TTemplate}
 */
const template = (w) =>
  w.schedule(
    w.on(
      w.week(1),
      w.mon(),
      w.all(),
      w.deploy(
        'ko-wai-koe',
        'blog',
        'example-blog',
        'reflections',
        'my-collection',
        'resources',
        'javascript-intro',
        'DOM-applying-classes',
        'DOM-interactions',
        'javascript-cafe',
        'javascript-methods',
        'javascript-kata',
        'tic-tac-toe',
        'javascript-carnival',
        'calculator',
        'minesweeper',
      ),
    ),
    w.on(
      w.week(6),
      w.fri(),
      w.all(),
      w.deploy('video-lectures', 'morning-quiz'),
    ),
    w.on(w.week(6), w.fri(), w.online(), w.deploy('remote-git-iam')),
    w.on(
      w.week(7),
      w.mon(),
      w.all(),
      w.deploy('two-truths-and-a-lie', 'kata-objects-and-arrays'),
    ),
    w.on(
      w.week(7),
      w.tue(),
      w.all(),
      w.deploy(
        'kata-types-modules',
        'kata-strings-numbers-modules',
        'kata-object-array',
        'kata-number-patterns',
        'kata-fizzbuzz',
      ),
    ),
    w.on(
      w.week(7),
      w.wed(),
      w.all(),
      w.deploy('kata-data-structures', 'bowling-kata'),
    ),
    w.on(w.week(7), w.thu(), w.all(), w.deploy('tdd-bowling-kata', 'conways')),
    w.on(
      w.week(7),
      w.fri(),
      w.all(),
      w.deploy('kata-typescript', 'whats-on-tvite'),
    ),
    w.on(
      w.week(8),
      w.mon(),
      w.all(),
      w.deploy('react-paws-for-effect', 'charlottes-web-log'),
    ),
    w.on(
      w.week(8),
      w.tue(),
      w.all(),
      w.deploy('react-state-kata', 'broken-kaleidoscope', 'enspiraled'),
    ),
    w.on(w.week(8), w.wed(), w.all(), w.deploy('worldwide-routing')),
    w.on(
      w.week(8),
      w.thu(),
      w.all(),
      w.deploy(
        'react-form-demo',
        'kata-react-forms',
        'boilerplate-react',
        'boilerplate-react-tw-routing',
        'boilerplate-react-routing',
        'lightning-talks',
      ),
    ),
    w.on(w.week(9), w.mon(), w.all(), w.deploy('consuming-clientside-apis')),
    w.on(w.week(9), w.tue(), w.all(), w.deploy('query-em-all')),
    w.on(w.week(9), w.wed(), w.all(), w.deploy('korihi', 'software-quality')),
    w.on(
      w.week(9),
      w.thu(),
      w.all(),
      w.deploy(
        'boilerplate-phase1',
        'boilerplate-phase1-tw',
        'boilerplate-phase1-routing',
      ),
    ),
    w.on(
      w.week(10),
      w.mon(),
      w.all(),
      w.deploy('express-server', 'art-gallery'),
    ),
    w.on(w.week(10), w.tue(), w.all(), w.deploy('pupparazzi')),
    w.on(w.week(10), w.wed(), w.all(), w.deploy('consuming-server-apis')),
    w.on(
      w.week(10),
      w.wed(),
      w.online(),
      w.deploy(
        'boilerplate-fullstack',
        'boilerplate-fullstack-routing',
        'ai-joker',
      ),
    ),
    w.on(
      w.week(10),
      w.thu(),
      w.all(),
      w.deploy(
        'boilerplate-react-api',
        'boilerplate-react-api-tw',
        'boilerplate-react-tw-routing',
      ),
    ),
    w.on(w.week(11), w.mon(), w.all(), w.deploy('knex-todo-cli')),
    w.on(
      w.week(11),
      w.tue(),
      w.all(),
      w.deploy('dreamfest', 'movie-facts', 'database-diagram'),
    ),
    w.on(w.week(11), w.wed(), w.all(), w.deploy('flight-club', 'ai-chatbot')),
    w.on(
      w.week(11),
      w.thu(),
      w.all(),
      w.deploy('boilerplate-fullstack', 'boilerplate-fullstack-routing'),
    ),
    w.on(w.week(12), w.mon(), w.all(), w.deploy('jwt-auth')),
    w.on(w.week(12), w.tue(), w.all(), w.deploy('todo-full-stack')),
    w.on(
      w.week(12),
      w.thu(),
      w.all(),
      w.deploy('boilerplate-fullstack-auth', 'ai-blog'),
    ),
    w.on(
      w.week(13),
      w.mon(),
      w.all(),
      w.deploy('ai-job-evaluator', 'supabase-local', 'diy-project'),
    ),
  )

export default template
