// file generated by sosij
module.exports = (on) => {
  // Cohort starting Mon Mar 14
  // week 1, day 1
  on('2022-03-14')
    .deploy('two-truths-and-a-lie', 'kata-objects-and-arrays')
    .to('butt-org')

  // week 1, day 2
  on('2022-03-15')
    .deploy(
      'kata-types-modules',
      'kata-strings-numbers-modules',
      'exercise-arrays',
      'object-array-practice',
      'kata-number-patterns'
    )
    .to('butt-org')

  // week 1, day 3
  on('2022-03-16')
    .deploy('kata-data-structures', 'bowling-kata', 'jest-demo')
    .to('butt-org')

  // week 1, day 4
  on('2022-03-17').deploy('tdd-bowling-kata', 'conways').to('butt-org')

  // week 1, day 5
  on('2022-03-18').deploy('ascii-art-reader').to('butt-org')

  // week 2, day 1
  on('2022-03-21').deploy('express-server', 'boilerplate-phase1').to('butt-org')

  // week 2, day 2
  on('2022-03-22').deploy('server-side-rendering', 'meowtown').to('butt-org')

  // week 2, day 3
  on('2022-03-23').deploy('pupparazzi').to('butt-org')

  // week 2, day 4
  on('2022-03-24').deploy('heroku-checklist', 'pupparazzi').to('butt-org')

  // week 3, day 1
  on('2022-03-28').deploy('knex-todo-cli').to('butt-org')

  // week 3, day 2
  on('2022-03-29').deploy('knex-joins-stories').to('butt-org')

  // week 3, day 3
  on('2022-03-30')
    .deploy('knex-relationships-stories', 'database-diagram')
    .to('butt-org')

  // week 3, day 4
  on('2022-03-31')
    .deploy('knex-forms-stories', 'lightning-talks')
    .to('butt-org')

  // week 4, day 1
  on('2022-04-04')
    .deploy('react-paws-for-effect', 'charlottes-web-log', 'react-minimal')
    .to('butt-org')

  // week 4, day 2
  on('2022-04-05')
    .deploy(
      'broken-kaleidoscope',
      'memory',
      'enspiraled',
      'boilerplate-react-webpack',
      'enzyme-examples'
    )
    .to('butt-org')

  // week 4, day 3
  on('2022-04-06').deploy('worldwide-routing').to('butt-org')

  // week 4, day 4
  on('2022-04-07').deploy('react-form-demo').to('butt-org')

  // week 5, day 1
  on('2022-04-11')
    .deploy(
      'charlottes-web-log-api',
      'web-api-stories',
      'boilerplate-express-api'
    )
    .to('butt-org')

  // week 5, day 2
  on('2022-04-12').deploy('react-to-web-api').to('butt-org')

  // week 5, day 3
  on('2022-04-13')
    .deploy('consuming-external-apis', 'boilerplate-react-webpack')
    .to('butt-org')

  // week 6, day 1
  on('2022-04-18').deploy('redux-minimal').to('butt-org')

  // week 6, day 2
  on('2022-04-19')
    .deploy('sweet-as-beers', 'react-redux-stories')
    .to('butt-org')

  // week 6, day 3
  on('2022-04-20')
    .deploy('async-redux-stories', 'sweet-as-organics-api', 'todo-full-stack')
    .to('butt-org')
}
